# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Fade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'fade_wheel',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=20)),
                ('word', models.CharField(max_length=40)),
                ('per_price', models.CharField(max_length=20)),
                ('all_price', models.CharField(max_length=20)),
                ('disoff', models.CharField(max_length=20)),
                ('category', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'goodslist',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=80)),
                ('t_content', models.CharField(max_length=80)),
                ('t_img', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'title',
            },
        ),
    ]
